# Generated by Django 4.2.13 on 2024-08-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='carbs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditem',
            name='fats',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditem',
            name='proteins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditem',
            name='serving_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditem',
            name='this_serving',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
