# Generated by Django 4.2.13 on 2024-08-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0003_fooditem_carbs_fooditem_fats_fooditem_proteins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_weight',
            field=models.IntegerField(),
        ),
    ]
