# Generated by Django 4.2.15 on 2024-08-16 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0005_standards'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Standards',
        ),
    ]
